export type GuideExample = { input: string; output: string; source: string };

export const GUIDE_EXAMPLES: Record<string, GuideExample> = {
  "1": {"input":"nums = [2,7,11,15], target = 9","output":"[0,1]","source":"https://leetcode.cn/problems/two-sum/description/"},
  "3": {"input":"s = \"abcabcbb\"","output":"3","source":"https://leetcode.cn/problems/longest-substring-without-repeating-characters/description/"},
  "4": {"input":"nums1 = [1,3], nums2 = [2]","output":"2.00000","source":"https://leetcode.cn/problems/median-of-two-sorted-arrays/description/"},
  "5": {"input":"s = \"babad\"","output":"\"bab\"","source":"https://leetcode.cn/problems/longest-palindromic-substring/description/"},
  "15": {"input":"nums = [-1,0,1,2,-1,-4]","output":"[[-1,-1,2],[-1,0,1]]","source":"https://leetcode.cn/problems/3sum/description/"},
  "19": {"input":"head = [1,2,3,4,5], n = 2","output":"[1,2,3,5]","source":"https://leetcode.cn/problems/remove-nth-node-from-end-of-list/description/"},
  "20": {"input":"s = \"()\"","output":"true","source":"https://leetcode.cn/problems/valid-parentheses/description/"},
  "21": {"input":"l1 = [1,2,4], l2 = [1,3,4]","output":"[1,1,2,3,4,4]","source":"https://leetcode.cn/problems/merge-two-sorted-lists/description/"},
  "22": {"input":"n = 3","output":"[\"((()))\",\"(()())\",\"(())()\",\"()(())\",\"()()()\"]","source":"https://leetcode.cn/problems/generate-parentheses/description/"},
  "23": {"input":"lists = [[1,4,5],[1,3,4],[2,6]]","output":"[1,1,2,3,4,4,5,6]","source":"https://leetcode.cn/problems/merge-k-sorted-lists/description/"},
  "25": {"input":"head = [1,2,3,4,5], k = 2","output":"[2,1,4,3,5]","source":"https://leetcode.cn/problems/reverse-nodes-in-k-group/description/"},
  "31": {"input":"nums = [1,2,3]","output":"[1,3,2]","source":"https://leetcode.cn/problems/next-permutation/description/"},
  "32": {"input":"s = \"(()\"","output":"2","source":"https://leetcode.cn/problems/longest-valid-parentheses/description/"},
  "33": {"input":"nums = [4,5,6,7,0,1,2], target = 0","output":"4","source":"https://leetcode.cn/problems/search-in-rotated-sorted-array/description/"},
  "42": {"input":"height = [0,1,0,2,1,0,1,3,2,1,2,1]","output":"6","source":"https://leetcode.cn/problems/trapping-rain-water/description/"},
  "46": {"input":"nums = [1,2,3]","output":"[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]","source":"https://leetcode.cn/problems/permutations/description/"},
  "53": {"input":"nums = [-2,1,-3,4,-1,2,1,-5,4]","output":"6","source":"https://leetcode.cn/problems/maximum-subarray/description/"},
  "54": {"input":"matrix = [[1,2,3],[4,5,6],[7,8,9]]","output":"[1,2,3,6,9,8,7,4,5]","source":"https://leetcode.cn/problems/spiral-matrix/description/"},
  "56": {"input":"intervals = [[1,3],[2,6],[8,10],[15,18]]","output":"[[1,6],[8,10],[15,18]]","source":"https://leetcode.cn/problems/merge-intervals/description/"},
  "69": {"input":"x = 4","output":"2","source":"https://leetcode.cn/problems/sqrtx/description/"},
  "72": {"input":"word1 = \"horse\", word2 = \"ros\"","output":"3","source":"https://leetcode.cn/problems/edit-distance/description/"},
  "76": {"input":"s = \"ADOBECODEBANC\", t = \"ABC\"","output":"\"BANC\"","source":"https://leetcode.cn/problems/minimum-window-substring/description/"},
  "82": {"input":"head = [1,2,3,3,4,4,5]","output":"[1,2,5]","source":"https://leetcode.cn/problems/remove-duplicates-from-sorted-list-ii/description/"},
  "88": {"input":"nums1 = [1,2,3,0,0,0], m = 3, nums2 = [2,5,6], n = 3","output":"[1,2,2,3,5,6]","source":"https://leetcode.cn/problems/merge-sorted-array/description/"},
  "92": {"input":"head = [1,2,3,4,5], left = 2, right = 4","output":"[1,4,3,2,5]","source":"https://leetcode.cn/problems/reverse-linked-list-ii/description/"},
  "93": {"input":"s = \"25525511135\"","output":"[\"255.255.11.135\",\"255.255.111.35\"]","source":"https://leetcode.cn/problems/restore-ip-addresses/description/"},
  "94": {"input":"root = [1,null,2,3]","output":"[1,3,2]","source":"https://leetcode.cn/problems/binary-tree-inorder-traversal/description/"},
  "102": {"input":"root = [3,9,20,null,null,15,7]","output":"[[3],[9,20],[15,7]]","source":"https://leetcode.cn/problems/binary-tree-level-order-traversal/description/"},
  "103": {"input":"root = [3,9,20,null,null,15,7]","output":"[[3],[20,9],[15,7]]","source":"https://leetcode.cn/problems/binary-tree-zigzag-level-order-traversal/description/"},
  "121": {"input":"prices = [7,1,5,3,6,4]","output":"5","source":"https://leetcode.cn/problems/best-time-to-buy-and-sell-stock/description/"},
  "124": {"input":"root = [1,2,3]","output":"6","source":"https://leetcode.cn/problems/binary-tree-maximum-path-sum/description/"},
  "141": {"input":"head = [3,2,0,-4], pos = 1","output":"true","source":"https://leetcode.cn/problems/linked-list-cycle/description/"},
  "142": {"input":"head = [3,2,0,-4], pos = 1","output":"返回索引为 1 的链表节点","source":"https://leetcode.cn/problems/linked-list-cycle-ii/description/"},
  "143": {"input":"head = [1,2,3,4]","output":"[1,4,2,3]","source":"https://leetcode.cn/problems/reorder-list/description/"},
  "146": {"input":"[\"LRUCache\",\"put\",\"put\",\"get\",\"put\",\"get\",\"put\",\"get\",\"get\",\"get\"]\n[[2],[1,1],[2,2],[1],[3,3],[2],[4,4],[1],[3],[4]]","output":"[null,null,null,1,null,-1,null,-1,3,4]","source":"https://leetcode.cn/problems/lru-cache/description/"},
  "148": {"input":"head = [4,2,1,3]","output":"[1,2,3,4]","source":"https://leetcode.cn/problems/sort-list/description/"},
  "160": {"input":"intersectVal = 8, listA = [4,1,8,4,5], listB = [5,6,1,8,4,5], skipA = 2, skipB = 3","output":"Intersected at '8'","source":"https://leetcode.cn/problems/intersection-of-two-linked-lists/description/"},
  "165": {"input":"version1 = \"1.2\", version2 = \"1.10\"","output":"-1","source":"https://leetcode.cn/problems/compare-version-numbers/description/"},
  "199": {"input":"root = [1,2,3,null,5,null,4]","output":"[1,3,4]","source":"https://leetcode.cn/problems/binary-tree-right-side-view/description/"},
  "200": {"input":"grid = [\n  ['1','1','1','1','0'],\n  ['1','1','0','1','0'],\n  ['1','1','0','0','0'],\n  ['0','0','0','0','0']\n]","output":"1","source":"https://leetcode.cn/problems/number-of-islands/description/"},
  "206": {"input":"head = [1,2,3,4,5]","output":"[5,4,3,2,1]","source":"https://leetcode.cn/problems/reverse-linked-list/description/"},
  "215": {"input":"nums = [3,2,1,5,6,4], k = 2","output":"5","source":"https://leetcode.cn/problems/kth-largest-element-in-an-array/description/"},
  "232": {"input":"[\"MyQueue\", \"push\", \"push\", \"peek\", \"pop\", \"empty\"]\n[[], [1], [2], [], [], []]","output":"[null, null, null, 1, 1, false]","source":"https://leetcode.cn/problems/implement-queue-using-stacks/description/"},
  "236": {"input":"root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1","output":"3","source":"https://leetcode.cn/problems/lowest-common-ancestor-of-a-binary-tree/description/"},
  "239": {"input":"nums = [1,3,-1,-3,5,3,6,7], k = 3","output":"[3,3,5,5,6,7]","source":"https://leetcode.cn/problems/sliding-window-maximum/description/"},
  "300": {"input":"nums = [10,9,2,5,3,7,101,18]","output":"4","source":"https://leetcode.cn/problems/longest-increasing-subsequence/description/"},
  "415": {"input":"num1 = \"11\", num2 = \"123\"","output":"\"134\"","source":"https://leetcode.cn/problems/add-strings/description/"},
  "704": {"input":"nums = [-1,0,3,5,9,12], target = 9","output":"4","source":"https://leetcode.cn/problems/binary-search/description/"},
  "1143": {"input":"text1 = \"abcde\", text2 = \"ace\"","output":"3","source":"https://leetcode.cn/problems/longest-common-subsequence/description/"},
  "补充题4": {"input":"nums = [5,2,3,1]","output":"[1,2,3,5]","source":"https://leetcode.cn/problems/sort-an-array/description/"},
};

