"use client";

import { useEffect, useMemo, useState } from "react";
import { PROBLEMS, UNITS, byTopic, difficultyLabel, type Problem, type TopicKey } from "./game-data";

type Screen = "map" | "library" | "review";
type Lesson = { unitIndex: number; levelIndex: number } | null;
const CODE_KEYWORDS = new Set(["for","while","if","else","elif","in","and","or","not","return","def","True","False","None","range","len","max","min","int","str","enumerate","self"]);

function sound(kind: "tap" | "correct" | "wrong", enabled: boolean) {
  if (!enabled || typeof window === "undefined") return;
  const Audio = window.AudioContext || (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Audio) return;
  const ctx = new Audio();
  const notes = kind === "correct" ? [523, 659, 784] : kind === "wrong" ? [180, 140] : [420];
  notes.forEach((frequency, i) => {
    const oscillator = ctx.createOscillator(); const gain = ctx.createGain();
    oscillator.type = kind === "wrong" ? "sawtooth" : "sine"; oscillator.frequency.value = frequency;
    gain.gain.setValueAtTime(.0001, ctx.currentTime + i * .08);
    gain.gain.exponentialRampToValueAtTime(kind === "tap" ? .025 : .07, ctx.currentTime + i * .08 + .01);
    gain.gain.exponentialRampToValueAtTime(.0001, ctx.currentTime + i * .08 + .12);
    oscillator.connect(gain); gain.connect(ctx.destination);
    oscillator.start(ctx.currentTime + i * .08); oscillator.stop(ctx.currentTime + i * .08 + .14);
  });
}

function DemoVisual({ problem, step }: { problem: Problem; step: number }) {
  const progress = Math.min(4, step);
  if (problem.id === "1") {
    const nums = [2, 7, 11, 15]; const index = Math.min(Math.max(step - 1, 0), 1);
    return <div className="visual hash-visual"><div className="target-pill">target = 9</div><div className="array-row">{nums.map((n, i) => <div className={`array-cell ${i === index ? "focus" : ""} ${step > 3 && i < 2 ? "matched" : ""}`} key={n}><b>{n}</b><small>{i === index ? `i=${i}, x=${n}` : `i=${i}`}</small></div>)}</div><div className="memory-card"><span>seen</span><code>{step < 3 ? "{}" : step < 5 ? "{2: 0}" : "{2: 0}  ✓ 需要 2"}</code></div></div>;
  }
  if (problem.topic === "hash") return <div className="visual hash-visual"><div className="window-track">{"abcabcbb".split("").map((c,i)=><span className={i <= progress ? "active" : ""} key={i}>{c}<small>{i}</small></span>)}</div><div className="pointer-row"><b style={{transform:`translateX(${progress*34}px)`}}>↑ right</b><em>left ↑</em></div><div className="memory-card"><span>窗口状态</span><code>长度 {progress + 1} · best {Math.min(progress + 1, 3)}</code></div></div>;
  if (problem.topic === "linked") return <div className="visual linked-visual"><div className="node-chain">{[1,2,3,4].map((n,i)=><div className={`node-wrap ${i <= progress ? "visited" : ""}`} key={n}><span>{n}</span>{i<3&&<b>{i < progress ? "←" : "→"}</b>}</div>)}</div><div className="memory-card"><span>指针</span><code>prev={Math.max(0,progress)} · cur={Math.min(4,progress+1)}</code></div></div>;
  if (problem.topic === "tree") return <div className="visual tree-visual"><div className={`tree-node root ${progress>0?"focus":""}`}>5</div><div className="branches">╱　╲</div><div className="tree-row"><span className={progress>1?"focus":""}>3</span><span className={progress>2?"focus":""}>8</span></div><div className="branches small">╱ ╲　╱ ╲</div><div className="tree-row leaves"><span>2</span><span>4</span><span>7</span><span>9</span></div></div>;
  if (problem.topic === "dp") return <div className="visual dp-visual"><div className="dp-label">状态表 dp</div><div className="array-row">{[0,1,1,2,3,5].map((n,i)=><div className={`array-cell ${i===progress?"focus":""} ${i<progress?"matched":""}`} key={i}><b>{n}</b><small>dp[{i}]</small></div>)}</div><div className="memory-card"><span>转移</span><code>旧状态 → 新状态</code></div></div>;
  if (problem.topic === "graph") return <div className="visual grid-visual">{Array.from({length:16},(_,i)=><span className={i <= progress*2 ? "visited" : i%3 ? "land" : ""} key={i}>{i <= progress*2 ? "✓" : i%3 ? "1" : "0"}</span>)}</div>;
  if (problem.topic === "stack") return <div className="visual stack-visual"><div className="stack-box">{["(","[","{"].slice(0,Math.max(1,progress)).map((x,i)=><span key={i}>{x}</span>)}</div><div className="memory-card"><span>栈顶</span><code>{progress > 2 ? "弹出并匹配" : "压入等待匹配"}</code></div></div>;
  return <div className="visual"><div className="array-row">{[4,1,7,3,6].map((n,i)=><div className={`array-cell ${i===progress?"focus":""} ${i<progress?"matched":""}`} key={i}><b>{n}</b><small>i={i}</small></div>)}</div><div className="memory-card"><span>当前动作</span><code>检查下标 {progress}，更新边界</code></div></div>;
}

function AppHeader({ xp, hearts, streak, soundOn, toggleSound }: { xp:number; hearts:number; streak:number; soundOn:boolean; toggleSound:()=>void }) {
  return <header className="topbar"><div className="brand"><span className="brand-mark">&lt;/&gt;</span><span>AlgoGo</span></div><div className="stats"><span>🔥 {streak}</span><span>💎 {xp}</span><span>❤️ {hearts}</span><button className="sound-toggle" onClick={toggleSound} aria-label="切换音效">{soundOn ? "♪" : "×"}</button></div></header>;
}

export default function Home() {
  const [screen, setScreen] = useState<Screen>("map"); const [activeUnit, setActiveUnit] = useState(0); const [lesson, setLesson] = useState<Lesson>(null);
  const [stage, setStage] = useState(0); const [demoStep, setDemoStep] = useState(0); const [playing, setPlaying] = useState(false);
  const [completed, setCompleted] = useState<string[]>([]); const [xp, setXp] = useState(120); const [hearts, setHearts] = useState(5); const [soundOn, setSoundOn] = useState(true);
  const [selectedQuiz, setSelectedQuiz] = useState<string[]>([]); const [orderAnswer, setOrderAnswer] = useState<string[]>([]); const [variableAnswers, setVariableAnswers] = useState<string[]>(["","",""]); const [lineAnswers, setLineAnswers] = useState<string[]>(["",""]);
  const [feedback, setFeedback] = useState<"idle"|"correct"|"wrong">("idle"); const [search, setSearch] = useState("");

  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("algogo-progress") || "null"); if (saved) { setCompleted(saved.completed || []); setXp(saved.xp ?? 120); setSoundOn(saved.soundOn ?? true); } } catch {} }, []);
  useEffect(() => { localStorage.setItem("algogo-progress", JSON.stringify({completed,xp,soundOn})); }, [completed,xp,soundOn]);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setDemoStep(s => s >= 5 ? 0 : s + 1), 900); return () => window.clearInterval(timer); }, [playing]);

  const unit = UNITS[activeUnit]; const unitProblems = byTopic(unit.key);
  const lessonProblem = lesson && lesson.levelIndex > 0 ? byTopic(UNITS[lesson.unitIndex].key)[lesson.levelIndex - 1] : null;
  const codeLines = useMemo(() => lessonProblem?.code.split("\n").filter(Boolean) ?? [], [lessonProblem]);
  const orderLines = useMemo(() => codeLines.slice(0, Math.min(6, codeLines.length)), [codeLines]);
  const shuffledLines = useMemo(() => [...orderLines].map((line,i,arr)=>arr[(i+2)%arr.length]), [orderLines]);
  const variables = useMemo(() => { const found = (lessonProblem?.code.match(/[A-Za-z_][A-Za-z0-9_]*/g) ?? []).filter(x => !CODE_KEYWORDS.has(x) && x.length > 1); return [...new Set(found)].slice(0,3); }, [lessonProblem]);
  const fillLines = useMemo(() => { const important = codeLines.filter(line => /for |while |if |return /.test(line)); return (important.length >= 2 ? important : codeLines).slice(0,2).map(x=>x.trim()); }, [codeLines]);
  const lessonKey = lesson ? `${UNITS[lesson.unitIndex].key}-${lesson.levelIndex === 0 ? "intro" : lessonProblem?.id}` : "";
  const resetExercise = () => { setStage(0); setDemoStep(0); setPlaying(false); setSelectedQuiz([]); setOrderAnswer([]); setVariableAnswers(["","",""]); setLineAnswers(["",""]); setFeedback("idle"); };
  const openLesson = (unitIndex:number, levelIndex:number) => { setActiveUnit(unitIndex); setLesson({unitIndex,levelIndex}); resetExercise(); sound("tap", soundOn); };
  const closeLesson = () => { setLesson(null); setPlaying(false); setFeedback("idle"); };
  const celebrate = () => { if (!completed.includes(lessonKey)) { setCompleted(c => [...c, lessonKey]); setXp(x => x + 20); } setFeedback("correct"); sound("correct", soundOn); navigator.vibrate?.([30,40,30]); };
  const fail = () => { setFeedback("wrong"); setHearts(h => Math.max(0,h-1)); sound("wrong", soundOn); navigator.vibrate?.(80); };
  const advance = () => { setFeedback("idle"); setStage(s=>s+1); sound("tap", soundOn); };
  const introOptions = lesson ? [...byTopic(UNITS[lesson.unitIndex].key).slice(0,3), ...byTopic(UNITS[(lesson.unitIndex+1)%UNITS.length].key).slice(0,2)] : [];
  const introCorrect = lesson ? introOptions.filter(p=>p.topic===UNITS[lesson.unitIndex].key).map(p=>p.id) : [];
  const checkIntro = () => selectedQuiz.length === introCorrect.length && selectedQuiz.every(id=>introCorrect.includes(id)) ? celebrate() : fail();
  const checkOrder = () => orderAnswer.length === orderLines.length && orderAnswer.every((x,i)=>x===orderLines[i]) ? (setFeedback("correct"),sound("correct",soundOn)) : fail();
  const checkVariables = () => variables.every((v,i)=>variableAnswers[i].trim()===v) ? (setFeedback("correct"),sound("correct",soundOn)) : fail();
  const checkLines = () => fillLines.every((v,i)=>lineAnswers[i].trim()===v) ? celebrate() : fail();
  const filtered = PROBLEMS.filter(p => `${p.id}${p.title}`.toLowerCase().includes(search.toLowerCase())); const completedProblems = completed.filter(x=>!x.endsWith("intro")).length;

  return <main className="app-shell">
    <AppHeader xp={xp} hearts={hearts} streak={Math.max(1,Math.ceil(completedProblems/3))} soundOn={soundOn} toggleSound={()=>setSoundOn(x=>!x)} />
    {screen === "map" && <><div className="unit-tabs" role="tablist">{UNITS.map((u,i)=><button style={{"--tab":u.color} as React.CSSProperties} className={activeUnit===i?"active":""} onClick={()=>setActiveUnit(i)} key={u.key}>{i+1}</button>)}</div>
      <section className="hero-card" style={{"--unit":unit.color,"--unit-shadow":unit.shadow} as React.CSSProperties}><div><span className="eyebrow">CODETOP TOP 100 · UNIT {activeUnit+1}</span><h1>{unit.title}</h1><p>{unit.description}</p></div><div className="hero-orb">{unit.icon}</div></section>
      <div className="unit-progress"><span style={{width:`${Math.round(completed.filter(x=>x.startsWith(unit.key)).length/(unitProblems.length+1)*100)}%`,background:unit.color}} /><b>{completed.filter(x=>x.startsWith(unit.key)).length}/{unitProblems.length+1}</b></div>
      <section className="path" aria-label={`${unit.title}学习路径`}>{[null,...unitProblems].map((problem,index) => { const key = `${unit.key}-${index===0?"intro":problem?.id}`; const done = completed.includes(key); const previousKey = index <= 1 ? `${unit.key}-intro` : `${unit.key}-${unitProblems[index-2].id}`; const available = index === 0 || completed.includes(previousKey) || completed.length === 0; return <div className={`path-row side-${index%3}`} key={key}><button className={`level-node ${done?"done":available?"current":"locked"}`} style={{"--node":unit.color,"--node-shadow":unit.shadow} as React.CSSProperties} onClick={()=>openLesson(activeUnit,index)} aria-label={index===0?`${unit.title}概念关`:problem?.title}><span>{done?"✓":index===0?"✦":problem?.id.replace("剑指 Offer ","O")}</span></button><span className="level-label">{index===0?"概念热身":problem?.title}</span>{problem && <small className="rank-label">TOP {problem.rank}</small>}</div>; })}</section>
      {activeUnit < UNITS.length-1 && <button className="next-unit" onClick={()=>setActiveUnit(x=>x+1)}><span className="unit-number">{String(activeUnit+2).padStart(2,"0")}</span><div><b>{UNITS[activeUnit+1].title}</b><small>{byTopic(UNITS[activeUnit+1].key).length} 道高频题</small></div><span>→</span></button>}</>}
    {screen === "library" && <section className="library-view"><span className="eyebrow dark">100 道 · 2026-09-13 快照</span><h1>CodeTop 高频题库</h1><div className="search-box">⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索题号或名称" /></div><div className="problem-list">{filtered.map(problem=>{ const ui=UNITS.findIndex(u=>u.key===problem.topic); const li=byTopic(problem.topic).findIndex(p=>p.id===problem.id)+1; return <button onClick={()=>openLesson(ui,li)} key={problem.id}><span className="problem-rank">{problem.rank}</span><div><b>LC {problem.id} · {problem.title}</b><small>{UNITS[ui].title} · {difficultyLabel(problem.difficulty)} · 频次 {problem.frequency}</small></div><span className={completed.includes(`${problem.topic}-${problem.id}`)?"mini-check complete":"mini-check"}>{completed.includes(`${problem.topic}-${problem.id}`)?"✓":"→"}</span></button> })}</div></section>}
    {screen === "review" && <section className="review-view"><span className="eyebrow dark">YOUR JOURNEY</span><h1>今日复习</h1><div className="mastery-card"><div className="mastery-ring"><b>{completedProblems}</b><small>/100</small></div><div><h2>掌握进度</h2><p>{completedProblems<10?"路径刚刚开始，坚持每天三关。":completedProblems<50?"节奏不错，开始加入盲写复习。":"已经越过半程，冲刺模拟面试！"}</p></div></div><h3>各单元掌握度</h3><div className="review-units">{UNITS.map((u,i)=>{const count=completed.filter(x=>x.startsWith(u.key)&&!x.endsWith("intro")).length; const total=byTopic(u.key).length; return <button key={u.key} onClick={()=>{setActiveUnit(i);setScreen("map")}}><span className="review-icon" style={{background:u.color}}>{u.icon}</span><div><b>{u.title}</b><span><i style={{width:`${count/total*100}%`,background:u.color}} /></span></div><small>{count}/{total}</small></button>})}</div></section>}

    {lesson && <div className="lesson-page" role="dialog" aria-modal="true"><header className="lesson-header"><button onClick={closeLesson}>×</button><div className="lesson-progress"><span style={{width:`${lesson.levelIndex===0?100:(stage+1)*25}%`,background:UNITS[lesson.unitIndex].color}} /></div><span>❤️ {hearts}</span></header>
      {lesson.levelIndex===0 ? <section className="lesson-content intro-lesson"><span className="lesson-kicker" style={{color:UNITS[lesson.unitIndex].color}}>UNIT {lesson.unitIndex+1} · 概念关</span><h2>{UNITS[lesson.unitIndex].title}</h2><div className="concept-icon" style={{background:UNITS[lesson.unitIndex].color}}>{UNITS[lesson.unitIndex].icon}</div><p className="lead">{UNITS[lesson.unitIndex].description}</p><div className="rule-card"><b>识别口诀</b><p>{UNITS[lesson.unitIndex].rule}</p></div><h3>选出属于这个主题的题目</h3><p className="hint">可多选，共 {introCorrect.length} 项</p><div className="quiz-options">{introOptions.map(option=><button className={selectedQuiz.includes(option.id)?"selected":""} onClick={()=>setSelectedQuiz(v=>v.includes(option.id)?v.filter(x=>x!==option.id):[...v,option.id])} key={option.id}><span>LC {option.id}</span>{option.title}<i>{selectedQuiz.includes(option.id)?"✓":""}</i></button>)}</div><Feedback state={feedback}/><button className="primary sticky-action" style={{"--button":UNITS[lesson.unitIndex].color,"--button-shadow":UNITS[lesson.unitIndex].shadow} as React.CSSProperties} onClick={feedback==="correct"?closeLesson:checkIntro}>{feedback==="correct"?"收下 20 XP，继续":"检查答案"}<span>→</span></button>{feedback==="correct"&&<Confetti />}</section>
      : lessonProblem && <section className="lesson-content"><span className="lesson-kicker" style={{color:UNITS[lesson.unitIndex].color}}>TOP {lessonProblem.rank} · {difficultyLabel(lessonProblem.difficulty)} · 频次 {lessonProblem.frequency}</span><h2>LC {lessonProblem.id} · {lessonProblem.title}</h2><div className="stage-chips"><span className={stage===0?"active":""}>演示</span><span className={stage===1?"active":""}>排序</span><span className={stage===2?"active":""}>变量</span><span className={stage===3?"active":""}>代码</span></div>
        {stage===0 && <><h3>看一遍算法如何流动</h3><p className="hint">播放时，高亮代码行与下方状态同步变化。</p><DemoVisual problem={lessonProblem} step={demoStep}/><div className="code-card">{codeLines.map((line,i)=><code className={i===demoStep%codeLines.length?"active":""} key={i}><em>{i+1}</em>{line}</code>)}</div><div className="demo-controls"><button onClick={()=>setDemoStep(x=>Math.max(0,x-1))}>←</button><button className="play" onClick={()=>setPlaying(x=>!x)}>{playing?"暂停":"▶ 播放"}</button><button onClick={()=>setDemoStep(x=>(x+1)%Math.max(1,codeLines.length))}>→</button></div><div className="narration"><b>第 {demoStep%codeLines.length+1} 行</b><p>{explainLine(codeLines[demoStep%codeLines.length], lessonProblem.topic)}</p></div><button className="primary sticky-action" style={{"--button":UNITS[lesson.unitIndex].color,"--button-shadow":UNITS[lesson.unitIndex].shadow} as React.CSSProperties} onClick={advance}>我看懂了，开始挑战 <span>→</span></button></>}
        {stage===1 && <><h3>把核心代码排回正确顺序</h3><p className="hint">依次点击下面的代码行；点击已选行可撤回。</p><div className="answer-slots">{orderAnswer.length?orderAnswer.map((line,i)=><button onClick={()=>setOrderAnswer(v=>v.filter((_,j)=>j!==i))} key={`${line}-${i}`}><em>{i+1}</em><code>{line}</code></button>):<p>答案区还是空的…</p>}</div><div className="line-bank">{shuffledLines.filter(line=>!orderAnswer.includes(line)).map((line,i)=><button onClick={()=>{setOrderAnswer(v=>[...v,line]);sound("tap",soundOn)}} key={`${line}-${i}`}><code>{line}</code></button>)}</div><Feedback state={feedback}/><button className="primary sticky-action" style={{"--button":UNITS[lesson.unitIndex].color,"--button-shadow":UNITS[lesson.unitIndex].shadow} as React.CSSProperties} onClick={feedback==="correct"?advance:checkOrder}>{feedback==="correct"?"继续":"检查顺序"}<span>→</span></button></>}
        {stage===2 && <><h3>补全 3 个关键变量</h3><p className="hint">变量名区分大小写，输入代码中使用的原名。</p><div className="variable-quiz">{variables.map((variable,i)=><label key={variable}><span>{i+1}</span><code>{maskVariable(codeLines.find(line=>line.includes(variable))||variable,variable)}</code><input value={variableAnswers[i]} onChange={e=>setVariableAnswers(v=>v.map((x,j)=>j===i?e.target.value:x))} placeholder="变量名" autoCapitalize="none" /></label>)}</div><Feedback state={feedback}/><button className="primary sticky-action" style={{"--button":UNITS[lesson.unitIndex].color,"--button-shadow":UNITS[lesson.unitIndex].shadow} as React.CSSProperties} onClick={feedback==="correct"?advance:checkVariables}>{feedback==="correct"?"继续":"检查变量"}<span>→</span></button></>}
        {stage===3 && <><h3>写出完整关键代码</h3><p className="hint">忽略行首缩进，但标点、变量与运算符需要一致。</p><div className="full-line-quiz">{fillLines.map((line,i)=><label key={line}><span>第 {codeLines.findIndex(x=>x.trim()===line)+1} 行</span><p>{lineHint(line)}</p><textarea value={lineAnswers[i]} onChange={e=>setLineAnswers(v=>v.map((x,j)=>j===i?e.target.value:x))} placeholder="在这里输入完整一行 Python 代码" spellCheck={false}/></label>)}</div><a className="leetcode-link" href={`https://leetcode.cn/problems/${lessonProblem.slug}/`} target="_blank" rel="noreferrer">在 LeetCode 打开原题 ↗</a><Feedback state={feedback}/><button className="primary sticky-action" style={{"--button":UNITS[lesson.unitIndex].color,"--button-shadow":UNITS[lesson.unitIndex].shadow} as React.CSSProperties} onClick={feedback==="correct"?closeLesson:checkLines}>{feedback==="correct"?"完成本关 · +20 XP":"提交代码"}<span>→</span></button>{feedback==="correct"&&<Confetti/>}</>}
      </section>}</div>}
    {!lesson && <nav className="bottom-nav"><button className={screen==="map"?"active":""} onClick={()=>setScreen("map")}><b>⌂</b><small>学习</small></button><button className={screen==="library"?"active":""} onClick={()=>setScreen("library")}><b>▦</b><small>题库</small></button><button className={screen==="review"?"active":""} onClick={()=>setScreen("review")}><b>◎</b><small>复习</small></button></nav>}
  </main>;
}

function Feedback({state}:{state:"idle"|"correct"|"wrong"}) { if(state==="idle") return null; return <div className={`feedback ${state}`}><b>{state==="correct"?"答对了！漂亮":"还差一点"}</b><span>{state==="correct"?"你已经抓住了这个模式。":"回看高亮代码，检查顺序、空格或变量名。"}</span></div>; }
function Confetti(){return <div className="confetti" aria-hidden="true">{Array.from({length:16},(_,i)=><i style={{"--x":`${(i%8)*13-45}px`,"--delay":`${(i%4)*.06}s`} as React.CSSProperties} key={i}/>)}</div>}
function maskVariable(line:string, variable:string){ return line.replace(new RegExp(`\\b${variable}\\b`), "____"); }
function lineHint(line:string){ if(line.startsWith("for ")) return "写出这一轮遍历语句"; if(line.startsWith("while ")) return "写出维持算法不变量的循环条件"; if(line.startsWith("if ")) return "写出关键分支判断"; if(line.startsWith("return ")) return "写出最终返回语句"; return "写出这行核心状态更新"; }
function explainLine(line:string, topic:TopicKey){ const clean=line.trim(); if(clean.startsWith("for ")) return "开始一次有边界的遍历；循环变量会指向当前需要处理的元素或状态。"; if(clean.startsWith("while ")) return "只要条件仍成立就继续推进指针，这个条件正是循环不变量的守门员。"; if(clean.startsWith("if ")) return "检查当前状态是否触发关键分支，避免无效搜索或错误更新。"; if(clean.startsWith("return ")) return "状态已经收敛，把最终答案返回给调用者。"; if(clean.includes("=")) return topic==="dp"?"用已经算出的旧状态更新当前状态。":"保存或更新当前变量，为下一步决策提供信息。"; return "执行当前算法动作，并保持核心不变量继续成立。"; }
